name: Build and Deploy GH Runner on ACI

on:
  push:
    branches: [main]
    paths: 
      - Dockerfile.aci
  workflow_dispatch:

env:
  IMAGE_NAME: aci-runner
  IMAGE_TAG: ${{ github.run_number }}
  RUNNER_REPOSITORY_URL: https://github.com/mattmajestic/windows-98
  RESOURCE_GROUP: azure-vm
  LOCATION: eastus

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Build and Push image to Azure Container Registry
      - name: Build and Push to ACR
        run: |
          docker build . -t majesticcoding.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker login majesticcoding.azurecr.io -u majesticcoding -p ${{ secrets.ACR_PASSWORD }}
          docker push majesticcoding.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy an Azure Container Instance
      - name: Deploy to Azure Container Instances
        uses: Azure/aci-deploy@v1
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          location: ${{ env.LOCATION }}
          cpu: 2
          dns-name-label: mattmajestic${{ github.run_number }}
          environment-variables: RUNNER_REPOSITORY_URL=${{ env.RUNNER_REPOSITORY_URL }}
          image: majesticcoding.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          name: actions-runner
          registry-login-server: majesticcoding.azurecr.io
          registry-username: majesticcoding
          registry-password: ${{ secrets.ACR_PASSWORD }}
          secure-environment-variables: GITHUB_TOKEN=${{ secrets.GIT_PAT }}
